# Generated by Django 3.0 on 2024-04-19 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_infomodel_extra_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infomodel',
            name='extra_label',
        ),
    ]
